# Polynomial Linear Regression

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import os

In [3]:
#Changing the directory
os.chdir('/content/drive/My Drive/CPCS 483/Midterm/Regression')

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Import Dataset

In [5]:
dataset = pd.read_csv('Data_regression.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [6]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


# Training the Polynomial Regression model on the whole dataset

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

# Training the Poly Linear Regression model on tre Training set

In [8]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

poly_reg = PolynomialFeatures(degree = 4)
X_poly = poly_reg.fit_transform(X_train)
poly_linear_mod = LinearRegression()
poly_linear_mod.fit(X_poly,y_train)

LinearRegression()

# Predicting the Test Set Result

In [9]:
y_pred = poly_linear_mod.predict(poly_reg.transform(X_test))
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[433.9805849  431.23      ]
 [457.96850722 460.01      ]
 [460.68596519 461.14      ]
 ...
 [470.3064789  468.9       ]
 [477.78573383 473.9       ]
 [440.02511302 437.07      ]]


# Calculate R2

In [10]:
from sklearn.metrics import r2_score  # Import the r2_score function from scikit-learn

# Calculate the R-squared (R²) score
R2 = r2_score(y_test, y_pred)

# Print the R-squared value
print("R-squared (R²):", R2)

# You can calculate and print accuracy if you prefer to refer to it as such
accuracy = R2 * 100
print("Accuracy: {:.2f}%".format(accuracy))

R-squared (R²): 0.9459731906012439
Accuracy: 94.60%
